[package]
name = "filters"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
globset = "0.4"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
proptest = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
libc = "0.2"
