[package]
name = "rsync-rs-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rsync-rs"
path = "src/main.rs"

[dependencies]
cli = { path = "../../crates/cli" }
engine = { path = "../../crates/engine" }
