[package]
name = "rsync-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rsync-rs"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cli = { path = "../../crates/cli" }

[workspace]
