[workspace]
members = [
    "crates/protocol",
    "crates/checksums",
    "crates/filters",
    "crates/walk",
    "crates/meta",
    "crates/compress",
    "crates/engine",
    "crates/transport",
    "crates/cli",
    "crates/fuzz",
    "bin/rsync-rs",
]
resolver = "2"

[package]
name = "rsync-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "crates/protocol" }
checksums = { path = "crates/checksums" }
cli = { path = "crates/cli" }
engine = { path = "crates/engine" }

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
serial_test = "2"
