[workspace]
members = [
    "crates/protocol",
    "crates/checksums",
    "crates/filters",
    "crates/walk",
    "crates/meta",
    "crates/compress",
    "crates/engine",
    "crates/transport",
    "crates/daemon",
    "crates/cli",
    "bin/oc-rsync",
]
resolver = "2"

[package]
name = "oc-rsync"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "crates/protocol" }
checksums = { path = "crates/checksums" }
cli = { path = "crates/cli" }
engine = { path = "crates/engine" }
filters = { path = "crates/filters" }
compress = { path = "crates/compress" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap_complete = "4"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
serial_test = "2"
nix = { version = "0.27", features = ["user", "fs"] }
xattr = "1.3"
posix-acl = "1.2"
transport = { path = "crates/transport" }
filetime = "0.2"
shell-words = "1.1"
wait-timeout = "0.2"

[[bin]]
name = "flag_matrix"
path = "tools/flag_matrix.rs"

[[bin]]
name = "gen-completions"
path = "tools/gen_completions.rs"

[features]
default = []
lz4 = ["engine/lz4"]
xattr = ["engine/xattr", "cli/xattr"]
acl = ["engine/acl", "cli/acl"]
blake3 = ["checksums/blake3", "engine/blake3", "cli/blake3"]
