codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        target: 0.95
        threshold: 0.0
    patch:
      default:
        target: 0.95
        threshold: 0.0
comment:
  layout: "reach, diff, flags, files"
  require_changes: false
