[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc_lexer = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "comment_lint"
path = "src/bin/comment_lint.rs"

[[bin]]
name = "status"
path = "src/bin/status.rs"
