[package]
name = "oc-rsync-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
engine = { path = "../engine" }
protocol = { path = "../protocol" }
filters = { path = "../filters" }
transport = { path = "../transport" }
users = "0.11"
compress = { path = "../compress" }
shell-words = "1.1"
meta = { path = "../meta", default-features = false }
daemon = { path = "../daemon" }
logging = { path = "../logging" }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"

[features]
default = []
xattr = ["engine/xattr"]
acl = ["engine/acl"]
blake3 = ["engine/blake3"]
