[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
engine = { path = "../engine" }
protocol = { path = "../protocol" }
