[package]
name = "compress"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1"
zstd = "0.13"
rust-lzo = "0.6.2"

[features]
default = []
# AVX-512 implementations (requires nightly Rust)
nightly = []
