[package]
name = "oc-rsync-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oc-rsync"
path = "src/main.rs"

[dependencies]
cli = { path = "../../crates/cli" }
engine = { path = "../../crates/engine" }
logging = { path = "../../crates/logging" }

[features]
default = []
xattr = ["engine/xattr", "cli/xattr"]
acl = ["engine/acl", "cli/acl"]
