[package]
name = "oc-rsync-bin"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "oc-rsync"
path = "src/main.rs"

[dependencies]
oc-rsync-cli = { path = "../../crates/cli" }
engine = { path = "../../crates/engine" }
logging = { path = "../../crates/logging" }
protocol = { path = "../../crates/protocol" }
clap = { version = "4" }

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
predicates = "3"

[features]
default = ["xattr", "acl"]
xattr = ["engine/xattr"]
acl = ["engine/acl"]
