[package]
name = "checksums"
version = "0.1.0"
edition = "2021"

[dependencies]
md-5 = "0.10"
sha1 = "0.10"
md4 = "0.10"
blake3 = { version = "1", optional = true }
blake2 = "0.10"
xxhash-rust = { version = "0.8", features = ["xxh3", "xxh64"] }

[features]
default = []
blake3 = ["dep:blake3"]
# AVX-512 implementations (requires nightly Rust)
nightly = []

[dev-dependencies]
hex = "0.4"
