[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
transport = { path = "../transport" }
nix = { version = "0.27", features = ["user", "fs"] }
protocol = { path = "../protocol" }
sd-notify = "0.4"

[dev-dependencies]
tempfile = "3"
