[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "../protocol" }
compress = { path = "../compress" }
nix = { version = "0.28", default-features = false, features = ["poll"] }
socket2 = { version = "0.5", features = ["all"] }
checksums = { path = "../checksums" }

[dev-dependencies]
tempfile = "3"
