[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
checksums = { path = "../checksums" }
walk = { path = "../walk" }
filters = { path = "../filters" }
compress = { path = "../compress" }

[dev-dependencies]
tempfile = "3"
compress = { path = "../compress" }
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "large_files"
harness = false

[features]
default = []
lz4 = ["compress/lz4"]
