[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1"
indexmap = "2"
compress = { path = "../compress" }
checksums = { path = "../checksums" }
filelist = { path = "../filelist" }
encoding_rs = "0.8"
subtle = "2"
tracing = "0.1"

[features]
default = []
