[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1"
indexmap = "2"
compress = { path = "../compress" }
checksums = { path = "../checksums" }

[features]
default = []
blake3 = ["checksums/blake3"]
