jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Single, authoritative toolchain setup for this job
      - name: Setup Rust (stable + components + cross targets)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy,rustfmt
          targets: x86_64-apple-darwin,x86_64-pc-windows-msvc
          cache: true
          # profile: minimal   # (optional) default is fine; components override profile anyway

      - name: Sanity: show toolchain/targets
        run: |
          rustup show
          rustup target list --installed
          rustc --version
          rustc --print sysroot
          rustc --target x86_64-apple-darwin --print target-libdir

      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libacl1-dev

      # Cross CHECK only (no linking to macOS/Windows SDKs)
      - name: Cargo check (cross targets)
        run: |
          cargo check --workspace --target x86_64-apple-darwin
          cargo check --workspace --target x86_64-pc-windows-msvc

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Verify comments
        run: make verify-comments

      - name: Validate interop matrix docs
        run: scripts/check-run-matrix-docs.sh

      - name: Check CLI help against transcript
        run: |
          cargo run --quiet --bin oc-rsync -- --help | tail -n +4 > /tmp/oc-rsync-help.txt
          diff -u tests/golden/help/oc-rsync.help /tmp/oc-rsync-help.txt
