name: Coverage

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --locked
      - name: Generate coverage report
        run: cargo llvm-cov --all-features --workspace --doctests --fail-under-lines 95 --fail-under-functions 95 --lcov --output-path lcov.info
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: lcov.info
